# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dg3wYiRsH8PsxYKRkYc43QiRe_K9wWmo
"""

!pip install streamlit
!pip install pyngrok

import streamlit as st
import cv2
import numpy as np
from tensorflow.keras.models import load_model
import tempfile
import os
from pyngrok import ngrok

model = load_model("model.h5")

def preprocess_frame(frame):
    frame_resized = cv2.resize(frame, (224, 224))
    frame_normalized = frame_resized / 255.0
    return frame_normalized

def predict_frame(frame):
    frame_processed = preprocess_frame(frame)
    prediction = model.predict(np.expand_dims(frame_processed, axis=0))
    return prediction[0][0]

#  Streamlit App
def main():
    st.title("Video Classification with Streamlit")
    st.write("Upload a video to classify its frames.")

    uploaded_file = st.file_uploader("Choose a video...", type=["avi", "mp4", "mov"])

    if uploaded_file is not None:
        tfile = tempfile.NamedTemporaryFile(delete=False)
        tfile.write(uploaded_file.read())
        video_path = tfile.name

        cap = cv2.VideoCapture(video_path)
        st.write("Processing video...")

        stframe = st.empty()
        predictions = []

        while cap.isOpened():
            ret, frame = cap.read()
            if not ret:
                break
            prediction = predict_frame(frame)
            predictions.append(prediction)

            frame = cv2.resize(frame, (640, 480))
            stframe.image(frame, caption=f"Prediction: {prediction:.2f}", channels="BGR")

        cap.release()

        avg_prediction = np.mean(predictions)
        st.write(f"Average Prediction for the video: {avg_prediction:.2f}")


        os.unlink(video_path)

if __name__ == "__main__":

    ngrok_tunnel = ngrok.connect(8501)
    print(f"Streamlit app running at: {ngrok_tunnel.public_url}")


    !streamlit run --server.port 8501 /usr/local/lib/python3.10/dist-packages/ipykernel_launcher.py

